# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171101_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_m',
            name='avatar',
        ),
        migrations.AddField(
            model_name='usuario_m',
            name='Avatar',
            field=models.FileField(null=True, upload_to=b'avatar/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='denuncia_m',
            name='img',
            field=models.FileField(null=True, upload_to=b'img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='denuncia_m',
            name='video',
            field=models.FileField(null=True, upload_to=b'videos/%Y/%m/%d'),
        ),
    ]
