# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171101_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Denuncia2',
        ),
    ]
