# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_entrada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
