# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubirImg_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(null=True, upload_to=b'img/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='denuncia_m',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubirImg_m'),
        ),
    ]
