# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171107_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia_m',
            name='img',
        ),
        migrations.AddField(
            model_name='subirimg_m',
            name='d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Denuncia_m'),
        ),
        migrations.AlterField(
            model_name='subirimg_m',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=b'img/%Y/%m/%d'),
        ),
    ]
