# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171107_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubirVideos_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=b'videos/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='denuncia_m',
            name='video',
        ),
        migrations.AddField(
            model_name='subirvideos_m',
            name='d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Denuncia_m'),
        ),
    ]
