# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171107_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subirvideos_m',
            old_name='d',
            new_name='a',
        ),
    ]
