# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_comentario_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario_m',
            name='denuncia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Denuncia_m'),
        ),
    ]
