# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_comentario_m_denuncia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_m',
            name='Correo',
        ),
    ]
